#! /bin/sh

sxhkd &
polybar -q status-desktop &

bspc config border_width 2
bspc config focused_border_color '#607D8B'

bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config focus_follows_pointer true

bspc monitor 'HDMI-0' -d '1-1' '1-2' '1-3' '1-4' '1-5'
bspc monitor 'DVI-I-0' -d '2-1' '2-2' '2-3' '2-4' '2-5'
