#! /bin/sh

sxhkd &
polybar -q status-laptop &
# python -u ~/.scripts/lemon.py  | lemonbar -g 1440x30+1440+0 &

bspc config border_width 1
bspc config focused_border_color '#607D8B'

bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

if xrandr | grep -q "HDMI-1 connected"; then
	bspc monitor HDMI-1 -d '1-1' '1-2' '1-3' '1-4' '1-5'
	bspc monitor eDP-1 -d '2-1' '2-2' '2-3' '2-4' '2-5'
elif xrandr | grep -q "^DP-1 connected"; then
	bspc monitor DP-1 -d '1-1' '1-2' '1-3' '1-4' '1-5'
	bspc monitor eDP-1 -d '2-1' '2-2' '2-3' '2-4' '2-5'
else
	bspc monitor -d '1' '2' '3' '4' '5'
fi
